apiVersion: "v1"
appVersion: "[[ .AppVersion ]]"
description: "Chart holding logging-operator."
home: "https://github.com/giantswarm/logging-operator"
name: "logging-operator"
version: "[[ .Version ]]"
