global:
  podSecurityStandards:
    enforced: false

aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: eu-central-1

image:
  name: "giantswarm/logging-operator"
  tag: ""

registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: "Cg=="

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 500Mi

ciliumNetworkPolicy:
  enabled: true

loggingOperator:
  vintageMode: true
  loggingEnabled: true

managementCluster:
  name: unknown
  baseDomain: "gaws.gigantic.io"
  provider: 
    kind: aws
