image:
  name: "giantswarm/logging-operator"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: "Cg=="

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

ciliumNetworkPolicy:
  enabled: true
