global:
  podSecurityStandards:
    enforced: false

image:
  name: "giantswarm/logging-operator"
  tag: ""

registry:
  domain: gsoci.azurecr.io
  pullSecret:
    dockerConfigJSON: "Cg=="

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 500Mi

networkPolicy:
  flavor: cilium

loggingOperator:
  vintageMode: true
  loggingEnabled: true

managementCluster:
  name: unknown
  insecureCA: false

profiling:
  enabled: false
  port: 6060
