image:
  name: "giantswarm/logging-operator"
  tag: "1.0.0" # TODO: can ABS automate update of this according to current release, like in Chart.yaml?

registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: "Cg=="

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

ciliumNetworkPolicy:
  enabled: true

loggingOperator:
  vintageMode: true
  installationName: unknown
  loggingEnabled: true
