global:
  podSecurityStandards:
    enforced: false

image:
  name: "giantswarm/logging-operator"
  tag: ""

registry:
  domain: gsoci.azurecr.io
  pullSecret:
    dockerConfigJSON: "Cg=="

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 150Mi

networkPolicy:
  flavor: cilium

loggingOperator:
  defaultNamespaces: "kube-system,giantswarm"
  excludeEventsFromNamespaces: []
  includeEventsFromNamespaces: []
  loggingEnabled: true
  loggingAgent: alloy
  eventsLogger: alloy

tracing:
  enabled: false

managementCluster:
  name: unknown
  insecureCA: false

profiling:
  enabled: false
  port: 6060
