{{- if .Values.loggingOperator.loggingEnabled -}}
{{- if .Capabilities.APIVersions.Has "objectstorage.giantswarm.io/v1alpha1" -}}
apiVersion: objectstorage.giantswarm.io/v1alpha1
kind: Bucket
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-loki-storage
  namespace: {{ include "resource.default.namespace" . }}
spec:
  name: {{ .Values.managementCluster.name }}-g8s-loki
  expirationPolicy:
    days: 100
  tags:
  - key: app
    value: loki
  - key: installation
    value: {{ .Values.managementCluster.name }}
  - key: managed-by
    value: logging-operator
  - key: name
    value: {{ .Values.managementCluster.name }}-g8s-loki
{{- end -}}
{{- end -}}
