{{- if eq .Values.managementCluster.provider.kind "capa" -}}
## Secret used to be able to connect to AWS account and be able to create the Loki Role for CAPA MCs
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-aws-credentials
  namespace: {{ include "resource.default.namespace" . }}
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.aws.accessKeyID | quote }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey | quote }}
type: Opaque
{{- end -}}
