apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: by-namespace
  labels:
    giantswarm.io/managed-by: logging-operator
spec:
  selector:
    matchExpressions:
    - key: giantswarm.io/logging
      operator: NotIn
      values:
        - disabled
  namespaceSelector:
    matchLabels:
      giantswarm.io/logging: enabled
  relabelings:
  - action: replace
    sourceLabels: ["__meta_kubernetes_namespace_label_namespace_giantswarm_io_logging_tenant"]
    targetLabel: "tenant_id"
    replacement: "$1"
    regex: "(.*)"
